package modelagem1;
// Generated 10/10/2015 20:13:35 by Hibernate Tools 4.3.1



/**
 * Hospedagem generated by hbm2java
 */
public class Hospedagem  implements java.io.Serializable {


     private int idhospedagem;
     private String nome;
     private int nquarto;
       private String preco;
     private int qtpessoas;
     private String dataentrada;
     private String datasaida;
   

    public Hospedagem() {
    }

    public Hospedagem(String nome, int nquarto,String preco, int qtpessoas, String dataentrada, String datasaida ) {
      this.idhospedagem=idhospedagem;
        this.nome = nome;
       this.nquarto = nquarto;
       this.preco = preco;
       this.qtpessoas = qtpessoas;
       this.dataentrada = dataentrada;
       this.datasaida = datasaida;
       
    }

    public int getIdhospedagem() {
        return idhospedagem;
    }

    public void setIdhospedagem(int idhospedagem) {
        this.idhospedagem = idhospedagem;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getNquarto() {
        return nquarto;
    }

    public void setNquarto(int nquarto) {
        this.nquarto = nquarto;
    }

    public String getPreco() {
        return preco;
    }

    public void setPreco(String preco) {
        this.preco = preco;
    }

    public int getQtpessoas() {
        return qtpessoas;
    }

    public void setQtpessoas(int qtpessoas) {
        this.qtpessoas = qtpessoas;
    }

    public String getDataentrada() {
        return dataentrada;
    }

    public void setDataentrada(String dataentrada) {
        this.dataentrada = dataentrada;
    }

    public String getDatasaida() {
        return datasaida;
    }

    public void setDatasaida(String datasaida) {
        this.datasaida = datasaida;
    }
   
   
   

}


