/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.mysql.jdbc.Connection;
import java.awt.print.PrinterException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dirceu
 */
public class ListaCandidato extends javax.swing.JFrame {

    /**
     * Creates new form ListaCandidato
     */
    public ListaCandidato() {
        initComponents();
            this.setLocationRelativeTo(null);
        this.setTitle("Lista Cliente");
        this.setIconImage(new ImageIcon(getClass(). getResource("ScreenHunter_06 Aug. 19 17.25.gif")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLista = new javax.swing.JButton();
        jLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLista.setBackground(new java.awt.Color(153, 255, 255));
        jLista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/filter.png"))); // NOI18N
        jLista.setText("Listar");
        jLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaActionPerformed(evt);
            }
        });
        getContentPane().add(jLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 80, 30));

        jLimpar.setBackground(new java.awt.Color(153, 255, 255));
        jLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/format1_16x16.gif"))); // NOI18N
        jLimpar.setText("Limpar");
        jLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 110, 30));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/print.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Rg", "Cpf", "Telefone", "Email", "Numero", "Rua", "Bairro", "Cidade", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 800, 400));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/search.png"))); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 100, 30));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 310, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/fd.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaActionPerformed
       try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
           conn =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
       String query="SELECT * FROM candidato ";
       PreparedStatement cmd;
       cmd= conn.prepareStatement(query);
       
       ResultSet rs;
       rs= cmd.executeQuery();
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       model.setNumRows(0);
       
       while(rs.next()){
           
       model.addRow(
               new Object[]{
                   rs.getString("Id"),
              rs.getString("Nome"),
                rs.getString("Rg"),
            rs.getString("CPF"),
               rs.getString("Telefone") ,
              rs.getString("Email"),
               rs.getString( "N"),
                rs.getString( "Rua"),
               rs.getString("Bairro"),
               rs.getString("Cidade"),
            rs.getString("Estado")
               }
       );
      
       }
       
        
        
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar a classe");
            
        } catch (SQLException ex) {
             System.out.println("Ocorreu error"+ ex.getMessage());
        }//Fim try
    }//GEN-LAST:event_jListaActionPerformed

    private void jLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimparActionPerformed
  DefaultTableModel tableModel =(DefaultTableModel) jTable1.getModel();  
  tableModel.setNumRows(0); 
    }//GEN-LAST:event_jLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {  
    // Imprime o coteudo da "jTable1":  
    jTable1.print(JTable.PrintMode.FIT_WIDTH);  
  
} catch (java.awt.print.PrinterException ex) {  
    JOptionPane.showMessageDialog(this, "Erro de impressão: " + ex.getMessage(), "Erro de impressão", JOptionPane.ERROR_MESSAGE);  
} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
           conn =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
       String query= "SELECT * FROM candidato WHERE nome  LIKE ? ";
       PreparedStatement cmd;
       cmd= conn.prepareStatement(query);
       cmd.setString(1,jTextField1.getText()+"%");
       ResultSet rs;
       rs= cmd.executeQuery();
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       model.setNumRows(0);
       
       while(rs.next()){
           
       model.addRow(
               new Object[]{
                   rs.getString("Id"),
              rs.getString("Nome"),
                rs.getString("Rg"),
            rs.getString("Cpf"),
               rs.getString("Telefone") ,
              rs.getString("Email"),
               rs.getString( "N"),
                  rs.getString("Rua"),
               rs.getString("Bairro"),
               rs.getString("Cidade"),
            rs.getString("Estado")
               }
       );
      
       }
       
        
        
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar a classe");
            
        } catch (SQLException ex) {
             System.out.println("Ocorreu error"+ ex.getMessage());
        }//Fim try
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLimpar;
    private javax.swing.JButton jLista;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
