/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author 102650
 */
public class Menu extends javax.swing.JFrame {
    ImageIcon imagem[]= new ImageIcon[8];
   int contador= 1;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
            this.setLocationRelativeTo(null);
        this.setTitle("Hotel");
        this.setIconImage(new ImageIcon(getClass().
        getResource("ScreenHunter_06 Aug. 19 17.25.gif")).getImage());
       for(int i=1; i<11;i++);{
    
        imagem[1]= new ImageIcon(getClass().getResource("ScreenHunter_06 Aug. 19 17.25.gif"));
        imagem[2]= new ImageIcon(getClass().getResource("ScreenHunter_07 Aug. 19 17.25.gif"));
        imagem[3]= new ImageIcon(getClass().getResource("ScreenHunter_90 Nov. 13 17.50.gif"));
        imagem[4]= new ImageIcon(getClass().getResource("ScreenHunter_92 Nov. 13 17.50.gif"));
        imagem[5]= new ImageIcon(getClass().getResource("ScreenHunter_93 Nov. 13 17.51.gif"));
        imagem[6]= new ImageIcon(getClass().getResource("ScreenHunter_94 Nov. 13 17.51.gif"));
        imagem[7]= new ImageIcon(getClass().getResource("image.jpg"));
    }
 jLabel2.setIcon (imagem[1]);
    }
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jFrame2 = new javax.swing.JFrame();
        jButton11 = new javax.swing.JButton();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jCliente = new javax.swing.JButton();
        jReserva = new javax.swing.JButton();
        jHospedagem = new javax.swing.JButton();
        jQuartos = new javax.swing.JButton();
        jProdutos = new javax.swing.JButton();
        jConsumo = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        jButton11.setText("jButton11");

        jMenu5.setText("jMenu5");

        jMenuItem19.setText("jMenuItem19");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCliente.setBackground(new java.awt.Color(153, 255, 255));
        jCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCliente.setForeground(new java.awt.Color(51, 153, 255));
        jCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/user8_16x16.gif"))); // NOI18N
        jCliente.setText("  CLIENTE    ");
        jCliente.setBorder(null);
        jCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteActionPerformed(evt);
            }
        });
        jCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jClienteKeyPressed(evt);
            }
        });
        getContentPane().add(jCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 280, 40));

        jReserva.setBackground(new java.awt.Color(153, 255, 255));
        jReserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jReserva.setForeground(new java.awt.Color(51, 153, 255));
        jReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/user8_(edit)_16x16.gif"))); // NOI18N
        jReserva.setText("RESERVA");
        jReserva.setBorder(null);
        jReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReservaActionPerformed(evt);
            }
        });
        jReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jReservaKeyPressed(evt);
            }
        });
        getContentPane().add(jReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 40));

        jHospedagem.setBackground(new java.awt.Color(153, 255, 255));
        jHospedagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jHospedagem.setForeground(new java.awt.Color(51, 153, 255));
        jHospedagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/finances_(edit)_16x16.gif"))); // NOI18N
        jHospedagem.setText("HOSPEDAGEM");
        jHospedagem.setBorder(null);
        jHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHospedagemActionPerformed(evt);
            }
        });
        jHospedagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jHospedagemKeyPressed(evt);
            }
        });
        getContentPane().add(jHospedagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 280, 40));

        jQuartos.setBackground(new java.awt.Color(153, 255, 255));
        jQuartos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jQuartos.setForeground(new java.awt.Color(51, 153, 255));
        jQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/house.png"))); // NOI18N
        jQuartos.setText("QUARTO");
        jQuartos.setBorder(null);
        jQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuartosActionPerformed(evt);
            }
        });
        jQuartos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jQuartosKeyPressed(evt);
            }
        });
        getContentPane().add(jQuartos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 280, 40));

        jProdutos.setBackground(new java.awt.Color(153, 255, 255));
        jProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jProdutos.setForeground(new java.awt.Color(51, 153, 255));
        jProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/basket.png"))); // NOI18N
        jProdutos.setText("PRODUTO");
        jProdutos.setBorder(null);
        jProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutosActionPerformed(evt);
            }
        });
        jProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jProdutosKeyPressed(evt);
            }
        });
        getContentPane().add(jProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 280, 40));

        jConsumo.setBackground(new java.awt.Color(153, 255, 255));
        jConsumo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jConsumo.setForeground(new java.awt.Color(51, 153, 255));
        jConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/basket_add.png"))); // NOI18N
        jConsumo.setText("CONSUMO");
        jConsumo.setBorder(null);
        jConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsumoActionPerformed(evt);
            }
        });
        jConsumo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jConsumoKeyPressed(evt);
            }
        });
        getContentPane().add(jConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, 40));

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 153, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/application_tile_horizontal.png"))); // NOI18N
        jButton7.setText("SAIR");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 280, 80));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/resultset_previous.png"))); // NOI18N
        jButton1.setText("ANTERIOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 170, 30));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/resultset_next.png"))); // NOI18N
        jButton2.setText("PROXIMO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/image.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 380, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/fd.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 830, 500));

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(153, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(102, 255, 255));
        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(51, 153, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/application_view_columns.png"))); // NOI18N
        jMenu1.setText("CADASTROS");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem1.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem1.setText("Cadastro Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        jMenuItem2.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem2.setText("Cadastro Quarto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMenuItem3.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem3.setText("Cadastro Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, 0));
        jMenuItem8.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem8.setText("Cadastro Hospedagem");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        jMenuItem10.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem10.setText("Cadastro Consumo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        jMenuItem11.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem11.setText("Cadastro Reserva");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(51, 153, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ordered_list_16x16.gif"))); // NOI18N
        jMenu2.setText("LISTAS");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem4.setText("Lista Quarto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem5.setText("Lista Cliente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem7.setText("Lista Produto");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem9.setText("Lista Hospedagem");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem12.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem12.setText("Lista Reserva");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem14.setForeground(new java.awt.Color(51, 153, 255));
        jMenuItem14.setText("Lista Consumo");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setForeground(new java.awt.Color(51, 153, 255));
        jMenuItem6.setText("Lista Produto Consumido");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(51, 153, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/chart_pie.png"))); // NOI18N
        jMenu3.setText("RELATORIOS");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem18.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem18.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem18.setText("Relatorio Diario");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem16.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem16.setText("Relatorio Mensal");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuItem17.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem17.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem17.setText("Relatorio Anual");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(51, 153, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/computer1_16x16.gif"))); // NOI18N
        jMenu4.setText("SOFTWARE");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem13.setForeground(new java.awt.Color(51, 153, 255));
        jMenuItem13.setText("Autor");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem15.setForeground(new java.awt.Color(51, 153, 255));
        jMenuItem15.setText("Ajuda");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        jMenu7.setForeground(new java.awt.Color(0, 153, 255));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/pictures.png"))); // NOI18N
        jMenu7.setText("IMAGENS");
        jMenu7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem21.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem21.setText("Enviar Imagem");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        jMenuBar1.add(jMenu7);

        jMenu6.setForeground(new java.awt.Color(0, 153, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/group_key.png"))); // NOI18N
        jMenu6.setText("SEGURANCA");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem20.setForeground(new java.awt.Color(0, 153, 255));
        jMenuItem20.setText("Modificar Senha");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenuBar1.add(jMenu6);

        jMenu8.setForeground(new java.awt.Color(0, 153, 255));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/date_magnify.png"))); // NOI18N
        jMenu8.setText("DATA");
        jMenu8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu9.setForeground(new java.awt.Color(0, 153, 255));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/hourglass.png"))); // NOI18N
        jMenu9.setText("HORA");
        jMenu9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    NewMasterProduto form= new NewMasterProduto();
        form.main(null);
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 NewMasterDetailForm form= new NewMasterDetailForm();
        form.main(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      NewMasterQuarto form= new     NewMasterQuarto();
        form.main(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
     ListaQuarto form= new  ListaQuarto();
     form.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
      ListaCandidato form= new  ListaCandidato();
     form.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     if (javax.swing.JOptionPane.showConfirmDialog(jButton7,
                "Tem certeza que deseja sair?", "Sair do sistema",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE) == javax.swing.JOptionPane.YES_OPTION){
                System.exit(0);}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteActionPerformed
      NewMasterDetailForm form= new   NewMasterDetailForm();
     form.main(null);
    }//GEN-LAST:event_jClienteActionPerformed

    private void jQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuartosActionPerformed
         NewMasterQuarto form= new  NewMasterQuarto();
     form.main(null);
    }//GEN-LAST:event_jQuartosActionPerformed

    private void jProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutosActionPerformed
 NewMasterProduto form= new NewMasterProduto();
        form.main(null);
    }//GEN-LAST:event_jProdutosActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      ListaProduto form= new     ListaProduto();
      form.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
     NewMasterHospedagem form= new  NewMasterHospedagem();
        form.main(null);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHospedagemActionPerformed
       NewMasterHospedagem form= new  NewMasterHospedagem();
        form.main(null);
    }//GEN-LAST:event_jHospedagemActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       ListaHospedagem form= new ListaHospedagem();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsumoActionPerformed
        NewMasterConsumo form= new NewMasterConsumo();
        form.main(null);
    }//GEN-LAST:event_jConsumoActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
         NewMasterConsumo form= new NewMasterConsumo();
        form.main(null);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReservaActionPerformed
          NewMasterReserva form= new NewMasterReserva();
        form.main(null);
    }//GEN-LAST:event_jReservaActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        NewMasterReserva form= new NewMasterReserva();
        form.main(null);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       ListaReserva form= new ListaReserva();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
       Autor form= new Autor();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
      
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        ListaConsumo form= new ListaConsumo();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
     Desktop desktop = null;  
    //Primeiro verificamos se é possível a integração com o desktop  
    if (!Desktop.isDesktopSupported())  
        throw new IllegalStateException("Desktop resources not supported!");  
      
    desktop = Desktop.getDesktop();  
    //Agora vemos se é possível disparar o browser default  
    if (!desktop.isSupported(Desktop.Action.BROWSE))  
        throw new IllegalStateException("No default browser set!");  
      
    try {  
        URI uri = new URI("http://localhost/Help/ajuda.html");  
        desktop.browse(uri);  
    } catch (URISyntaxException e1) {  
        e1.printStackTrace();  
    } catch (IOException e) {  
        e.printStackTrace();  
    }    
        
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ListaProdutoConsumido form= new  ListaProdutoConsumido();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
       RelatorioMensal form= new RelatorioMensal();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
       RelatorioMensal form= new RelatorioMensal();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
       RelatorioMensal form= new RelatorioMensal();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(contador==10){
         contador=0;
     }
     contador++;
     jLabel2.setIcon(imagem[contador]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(contador==1){
         contador=11;
     }
     contador--;
     jLabel2.setIcon(imagem[contador]);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        EnviarImagem form= new  EnviarImagem();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jClienteKeyPressed
        NewMasterDetailForm form= new   NewMasterDetailForm();
     form.main(null);
    }//GEN-LAST:event_jClienteKeyPressed

    private void jConsumoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jConsumoKeyPressed
     NewMasterConsumo form= new    NewMasterConsumo();
     form.main(null);
    }//GEN-LAST:event_jConsumoKeyPressed

    private void jHospedagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jHospedagemKeyPressed
        NewMasterHospedagem form= new    NewMasterHospedagem();
     form.main(null);
    }//GEN-LAST:event_jHospedagemKeyPressed

    private void jReservaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jReservaKeyPressed
    NewMasterReserva form= new    NewMasterReserva();
     form.main(null);
    }//GEN-LAST:event_jReservaKeyPressed

    private void jQuartosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQuartosKeyPressed
       NewMasterQuarto form= new    NewMasterQuarto();
     form.main(null);
    }//GEN-LAST:event_jQuartosKeyPressed

    private void jProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProdutosKeyPressed
       NewMasterProduto form= new    NewMasterProduto();
     form.main(null);
    }//GEN-LAST:event_jProdutosKeyPressed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
         if (javax.swing.JOptionPane.showConfirmDialog(jButton7,
                "Tem certeza que deseja sair?", "Sair do sistema",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE) == javax.swing.JOptionPane.YES_OPTION){
                System.exit(0);}
    }//GEN-LAST:event_jButton7KeyPressed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
       LoginNovaSenha form= new LoginNovaSenha();
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        java.util.Date datasistema= new java.util.Date();
      SimpleDateFormat formato= new SimpleDateFormat("dd/MM/yyyy");
      jMenu8.setText(formato.format(datasistema));
      //hora
      
      Timer timer=new Timer(1000, new hora());
      timer.start();
                     
    }//GEN-LAST:event_formWindowOpened
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jCliente;
    private javax.swing.JButton jConsumo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JButton jHospedagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JButton jProdutos;
    private javax.swing.JButton jQuartos;
    private javax.swing.JButton jReserva;
    // End of variables declaration//GEN-END:variables


class hora implements ActionListener{
   
     public void actionPerformed(ActionEvent e){
     
         Calendar now= Calendar.getInstance();
         jMenu9.setText(String.format("%1$tH:%1$tM:%1$tS",now));
     }}

}//Fim da classe


