/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dirceu
 */
public class RecuperaSenha extends javax.swing.JFrame {

    /**
     * Creates new form RecuperaSenha
     */
    public RecuperaSenha() {
        initComponents();
        this.setTitle("Recuperar senha");
            this.setLocationRelativeTo(null);
         this.setIconImage(new ImageIcon(getClass(). getResource("ScreenHunter_06 Aug. 19 17.25.gif")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("USUARIO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 20));

        jUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsuarioFocusLost(evt);
            }
        });
        jUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 160, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 20));

        jCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCpfFocusLost(evt);
            }
        });
        jCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCpfMouseClicked(evt);
            }
        });
        getContentPane().add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ScreenHunter_71 Aug. 18 22.00.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/redo.png"))); // NOI18N
        jButton1.setText("PROXIMO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/fd.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsuarioMouseClicked
   try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select  *from login");
              ResultSet rs = st.getResultSet();
        
                while (rs.next()){
        if(!jUsuario.getText().equals(rs.getString("usuario"))){
     javax.swing.JOptionPane.showMessageDialog(null, "Usuario incorreto!","",2); return;
     }
                }
         } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jUsuario, e);
        }//Fim try
    }//GEN-LAST:event_jUsuarioMouseClicked

    private void jUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsuarioFocusLost
     try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select  *from login");
              ResultSet rs = st.getResultSet();
        
                while (rs.next()){
        if(!jUsuario.getText().equals(rs.getString("usuario"))){
     javax.swing.JOptionPane.showMessageDialog(null, "Usuario incorreto!","",2); return;
     }
                }
         } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jUsuario, e);
        }//Fim try
    }//GEN-LAST:event_jUsuarioFocusLost

    private void jCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCpfMouseClicked
     
    }//GEN-LAST:event_jCpfMouseClicked

    private void jCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCpfFocusLost
         
    }//GEN-LAST:event_jCpfFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select  *from candidato");
              ResultSet rs = st.getResultSet();
        
                while (rs.next()){
        if(jCpf.getText().equals(rs.getString("cpf"))){
          new TelaLogin().setVisible(true);
          this.dispose(); 
          return;
        }else{
          javax.swing.JOptionPane.showMessageDialog(null, "Cpf nao confere!","",2); 
        return;
        }
                }
         } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jCpf, e);
        }//Fim try
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select  *from candidato");
              ResultSet rs = st.getResultSet();
        
                while (rs.next()){
        if(jCpf.getText().equals(rs.getString("cpf"))){
          new TelaLogin().setVisible(true);
          this.dispose();
          return;
        }else{
          javax.swing.JOptionPane.showMessageDialog(null, "Cpf nao confere!","",2); 
        return;
        }
                }
         } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jCpf, e);
        }//Fim try
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jUsuario;
    // End of variables declaration//GEN-END:variables
}
