/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import com.mysql.jdbc.Connection;
import controle.CtrlHospedagem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import modelagem1.Hospedagem;

/**
 *
 * @author Dirceu
 */
   public class TelaHospedagem extends javax.swing.JFrame {
    private CtrlHospedagem hospedagem;
  private NewMasterDetailForm veioDoNewMasterDetailForm  ;

    /**
     * Creates new form TelaCandidato
     */
    public  TelaHospedagem() {
        initComponents();
            this.setLocationRelativeTo(null);
         this.jIdhospedagem.setVisible(false);
        this.setTitle("Hospedagem");
         this.setIconImage(new ImageIcon(getClass(). getResource("ScreenHunter_06 Aug. 19 17.25.gif")).getImage());
          hospedagem= new CtrlHospedagem(); 
    }
public void  enviaPalavra (NewMasterDetailForm veiDo1,  String  nome){
             
              jNome.setText(nome);}


public void  enviaNome (NewMasterReserva veiDo1,  String  nome){
             
              jNome.setText(nome);}

TelaConsumo janela2= new TelaConsumo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("hotel?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        hospedagemQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Hospedagem h");
        hospedagemList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : hospedagemQuery.getResultList();
        hospedagemQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Hospedagem h");
        hospedagemList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : hospedagemQuery1.getResultList();
        hospedagemQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Hospedagem h");
        hospedagemList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : hospedagemQuery2.getResultList();
        hospedagemQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Hospedagem h");
        hospedagemList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : hospedagemQuery3.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jAdicionar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jIdhospedagem = new javax.swing.JTextField();
        jNome = new javax.swing.JTextField();
        jNquarto = new javax.swing.JTextField();
        jQtpessoas = new javax.swing.JTextField();
        jPreco = new javax.swing.JTextField();
        jDataentrada = new javax.swing.JFormattedTextField();
        jDatasaida = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTextField11.setText("jTextField11");

        jButton6.setText("jButton6");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ScreenHunter_05 May. 13 15.56.gif"))); // NOI18N

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel2.setText("Quarto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel3.setText("Pessoas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 60, 20));

        jLabel4.setText("Dataentrada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel6.setText("Preco:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, 20));

        jAdicionar.setBackground(new java.awt.Color(153, 255, 255));
        jAdicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/filesave.png"))); // NOI18N
        jAdicionar.setText("Salvar");
        jAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 170, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 128, -1, -1));

        jLabel12.setText("Datasaida:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/reload.png"))); // NOI18N
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 170, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, hospedagemList3, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idhospedagem}"));
        columnBinding.setColumnName("Idhospedagem");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nquarto}"));
        columnBinding.setColumnName("Quarto");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${preco}"));
        columnBinding.setColumnName("Preco");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${qtpessoas}"));
        columnBinding.setColumnName("Qtpessoas");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${datasaida}"));
        columnBinding.setColumnName("Datasaida");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataentrada}"));
        columnBinding.setColumnName("Dataentrada");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 780, 230));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/print.png"))); // NOI18N
        jButton3.setText("Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 170, -1));

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/redo.png"))); // NOI18N
        jButton4.setText("Consumo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 170, -1));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idhospedagem}"), jIdhospedagem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jIdhospedagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 60, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), jNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNomeMouseClicked(evt);
            }
        });
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 300, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nquarto}"), jNquarto, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jNquarto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNquartoFocusLost(evt);
            }
        });
        jNquarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNquartoMouseClicked(evt);
            }
        });
        getContentPane().add(jNquarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.qtpessoas}"), jQtpessoas, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jQtpessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQtpessoasMouseClicked(evt);
            }
        });
        getContentPane().add(jQtpessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 60, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.preco}"), jPreco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPrecoMouseClicked(evt);
            }
        });
        getContentPane().add(jPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 60, -1));

        try {
            jDataentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataentrada}"), jDataentrada, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jDataentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, -1));

        try {
            jDatasaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datasaida}"), jDatasaida, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jDatasaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 110, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/edit_add.png"))); // NOI18N
        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 170, -1));

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/application_view_columns.png"))); // NOI18N
        jButton7.setText("Lista Hospedagem");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/fd.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarActionPerformed
        if(jNome.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Nome campo obrigatório","",2);
    return;

}if(jNquarto.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Quarto campo obrigatório","",2);
    return;
        }if(jPreco.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Preco campo obrigatório","",2);
    return;
    }if(jDataentrada.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Data campo obrigatório","",2);
    return;}
      javax.swing.JOptionPane.showMessageDialog(null, "Registro salvo com sucesso");
       
      hospedagem.adicionar(this.telaHospedagem());
     this.hospedagemTela(hospedagem.exibir());
    
    
    }//GEN-LAST:event_jAdicionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
TelaHospedagem form= new TelaHospedagem();
dispose();
form.setVisible(true);
        
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try {  
    // Imprime o coteudo da "jTable1":  
    jTable1.print(JTable.PrintMode.FIT_WIDTH);  
  
} catch (java.awt.print.PrinterException ex) {  
    JOptionPane.showMessageDialog(this, "Erro de impressão: " + ex.getMessage(), "Erro de impressão", JOptionPane.ERROR_MESSAGE);  
} 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
               if(!jIdhospedagem.getText().isEmpty())
                 if(!jNome.getText().isEmpty())                       
               {
      if(janela2==null)
       {
          
 janela2= new TelaConsumo();
     janela2.setVisible(true);
             
       }else{
        
       janela2.setVisible(true);
      }
     janela2.enviaHospedagem(this, jIdhospedagem.getText() ) ;
          janela2.enviaNome(this, jNome.getText() ) ;
        }
                  
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jNquartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNquartoMouseClicked
      try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select * from quarto ");
              ResultSet rs = st.getResultSet();
              
              JPopupMenu popup1 = new JPopupMenu();
               JPopupMenu popup2 = new JPopupMenu();
                 JPopupMenu popup3 = new JPopupMenu();
                   JPopupMenu popup4 = new JPopupMenu();
                    JPopupMenu popup5 = new JPopupMenu();
                     JPopupMenu popup6 = new JPopupMenu();
                      JPopupMenu popup7 = new JPopupMenu();
                       JPopupMenu popup8 = new JPopupMenu();
                        JPopupMenu popup9 = new JPopupMenu();
                         JPopupMenu popup10 = new JPopupMenu();
   
                while (rs.next()){
         
                 // Especifica os dados em ordena.
             
         JMenuItem item = new JMenuItem(rs.getString("numero"));
        item.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
            jNquarto.setText(((JMenuItem) e.getSource()).getText());
            }
        });
         JMenuItem item1 = new JMenuItem( rs.getString("descrisao"));
        item1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
          
            }
        });
                //Adiciona item ao jText
              popup1.add(item);
              popup2.add(item);
              popup3.add(item);
              popup4.add(item);
               popup5.add(item);
              popup6.add(item);
              popup7.add(item);
              popup8.add(item);
               popup9.add(item);
              popup10.add(item);
              
               popup1.add(item1);
              popup2.add(item1);
              popup3.add(item1);
              popup4.add(item1);
               popup5.add(item1);
              popup6.add(item1);
              popup7.add(item1);
              popup8.add(item1);
               popup9.add(item1);
              popup10.add(item1);
              
                //Mostra na Tela
              popup1.show(jNquarto, 0, 30);
              popup2.show(jNquarto, 0, 30);
              popup3.show(jNquarto, 0, 30);
              popup4.show(jNquarto, 0, 30);
              popup5.show(jNquarto, 0, 30);
              popup6.show(jNquarto, 0, 30);
              popup7.show(jNquarto, 0, 30);
              popup8.show(jNquarto, 0, 30);
              popup9.show(jNquarto, 0, 30);
              popup10.show(jNquarto, 0, 30);
           
    
                }
             
                
           
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jNquarto, e);
        }//Fim try
    }//GEN-LAST:event_jNquartoMouseClicked

    private void jPrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrecoMouseClicked
        try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select * from quarto ");
              ResultSet rs = st.getResultSet();
              
              JPopupMenu popup1 = new JPopupMenu();
               JPopupMenu popup2 = new JPopupMenu();
                 JPopupMenu popup3 = new JPopupMenu();
                   JPopupMenu popup4 = new JPopupMenu();
                    JPopupMenu popup5 = new JPopupMenu();
                     JPopupMenu popup6 = new JPopupMenu();
                      JPopupMenu popup7 = new JPopupMenu();
                       JPopupMenu popup8 = new JPopupMenu();
                        JPopupMenu popup9 = new JPopupMenu();
                         JPopupMenu popup10 = new JPopupMenu();
   
                while (rs.next()){
         
                 // Especifica os dados em ordena.
            JMenuItem item = new JMenuItem(rs.getString("numero"));
        item.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           
            }
        }); 
         JMenuItem item1 = new JMenuItem(rs.getString("descrisao"));
        item1.addActionListener(new ActionListener() {
      
            public void actionPerformed(ActionEvent e) {
          
            }
        });
         JMenuItem item2 = new JMenuItem( rs.getString("preco"));
        item2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
            jPreco.setText(((JMenuItem) e.getSource()).getText());
            }
        }); 
        
                //Adiciona item ao jText
              popup1.add(item);
              popup2.add(item);
              popup3.add(item);
              popup4.add(item);
               popup5.add(item);
              popup6.add(item);
              popup7.add(item);
              popup8.add(item);
               popup9.add(item);
              popup10.add(item);
              
               popup1.add(item1);
              popup2.add(item1);
              popup3.add(item1);
              popup4.add(item1);
               popup5.add(item1);
              popup6.add(item1);
              popup7.add(item1);
              popup8.add(item1);
               popup9.add(item1);
              popup10.add(item1);
              
                popup1.add(item2);
              popup2.add(item2);
              popup3.add(item2);
              popup4.add(item2);
               popup5.add(item2);
              popup6.add(item2);
              popup7.add(item2);
              popup8.add(item2);
               popup9.add(item2);
              popup10.add(item2);
              
                //Mostra na Tela
              popup1.show(jPreco, 0, 30);
              popup2.show(jPreco, 0, 30);
              popup3.show(jPreco, 0, 30);
              popup4.show(jPreco, 0, 30);
              popup5.show(jPreco, 0, 30);
              popup6.show(jPreco, 0, 30);
              popup7.show(jPreco, 0, 30);
              popup8.show(jPreco, 0, 30);
              popup9.show(jPreco, 0, 30);
              popup10.show(jPreco, 0, 30);
           
    
                }
             
                
           
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jPreco, e);
        }//Fim try
    }//GEN-LAST:event_jPrecoMouseClicked

    private void jQtpessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQtpessoasMouseClicked
         //cria o primeiro item do menu e atribui uma ação pra ele
        JMenuItem item1 = new JMenuItem("1");
        item1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("1");
            }
        });

        //cria o segundo item do menu e atribui uma ação pra ele
        JMenuItem item2 = new JMenuItem("2");
        item2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
               jQtpessoas.setText("2");
            }
        });

        //cria o terceiro item do menu e atribui uma ação pra ele
        JMenuItem item3 = new JMenuItem("3");
        item3.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("3");
            }
        });
         JMenuItem item4 = new JMenuItem("4");
        item4.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("4");
            }
        });
         JMenuItem item5 = new JMenuItem("5");
        item5.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("5");
            }
        });
         JMenuItem item6 = new JMenuItem("6");
        item6.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("6");
            }
        });


        //cria o menu popup e adiciona os 3 itens
        JPopupMenu popup = new JPopupMenu();
        popup.add(item1);
        popup.add(item2);
        popup.add(item3);
        popup.add(item4);
        popup.add(item5);
        popup.add(item6);

        //mostra na tela
        popup.show(jQtpessoas, 0, 30);

    }//GEN-LAST:event_jQtpessoasMouseClicked

    private void jNquartoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNquartoFocusLost
        try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT  *FROM reserva ORDER BY datasaida ASC");
              ResultSet rs = st.getResultSet();
        
                while (rs.next()){
        if(jNquarto.getText().equals(rs.getString("nquarto"))){
     javax.swing.JOptionPane.showMessageDialog(null, "Quarto "+(rs.getString("nquarto"))+" Reservado para:"+"\n"+
             "Data Entrada: "+(rs.getString("dataentrada"))+"\n"+"Data Saida: "+(rs.getString("datasaida")),"",0);
  
        }
                }
         } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jNquarto, e);
        }//Fim try
        
          try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT  *FROM hospedagem ORDER BY datasaida DESC");
              ResultSet rs = st.getResultSet();
        
                while (rs.next()){
        if(jNquarto.getText().equals(rs.getString("nquarto"))){
     javax.swing.JOptionPane.showMessageDialog(null, "Quarto "+(rs.getString("nquarto"))+" Ultima hospedagem:"+"\n"+
             "Data Entrada: "+(rs.getString("dataentrada"))+"\n"+"Data Saida: "+(rs.getString("datasaida")),"",0);
     return;
        }
                }
         } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jNquarto, e);
        }//Fim try
    }//GEN-LAST:event_jNquartoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jNome.setText(null);
        jNquarto.setText(null);
        jQtpessoas.setText(null);
        jDataentrada.setText(null);
        jPreco.setText(null);
        jDatasaida.setText(null);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNomeMouseClicked
   try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select * from candidato ");
              ResultSet rs = st.getResultSet();
              
               JPopupMenu popup1 = new JPopupMenu();
               JPopupMenu popup2 = new JPopupMenu();
               JPopupMenu popup3 = new JPopupMenu();
               JPopupMenu popup4 = new JPopupMenu();
               JPopupMenu popup5 = new JPopupMenu();
               JPopupMenu popup6 = new JPopupMenu();
               JPopupMenu popup7 = new JPopupMenu();
               JPopupMenu popup8 = new JPopupMenu();
               JPopupMenu popup9 = new JPopupMenu();
               JPopupMenu popup10 = new JPopupMenu();
   
                while (rs.next()){
         
                 // Especifica os dados em ordena.
                 JMenuItem item = new JMenuItem (rs.getString("nome"));
        item.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
         jNome.setText(((JMenuItem) e.getSource()).getText());
                   
            }
      
        });
           
            
        
                //Adiciona item ao jText
              popup1.add(item);
              popup2.add(item);
              popup3.add(item);
              popup4.add(item);
               popup5.add(item);
              popup6.add(item);
              popup7.add(item);
              popup8.add(item);
               popup9.add(item);
              popup10.add(item);
              
                //Mostra na Tela
              popup1.show(jNome, 0, 30);
              popup2.show(jNome, 0, 30);
              popup3.show(jNome, 0, 30);
              popup4.show(jNome, 0, 30);
              popup5.show(jNome, 0, 30);
              popup6.show(jNome, 0, 30);
              popup7.show(jNome, 0, 30);
              popup8.show(jNome, 0, 30);
              popup9.show(jNome, 0, 30);
              popup10.show(jNome, 0, 30);
           
    
                }
             
                
           
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jNome, e);
        }//Fim try
    }//GEN-LAST:event_jNomeMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       ListaHospedagem form = new ListaHospedagem();
       form.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHospedagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHospedagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHospedagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHospedagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHospedagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private java.util.List<modelagem.Hospedagem> hospedagemList;
    private java.util.List<modelagem.Hospedagem> hospedagemList1;
    private java.util.List<modelagem.Hospedagem> hospedagemList2;
    private java.util.List<modelagem.Hospedagem> hospedagemList3;
    private javax.persistence.Query hospedagemQuery;
    private javax.persistence.Query hospedagemQuery1;
    private javax.persistence.Query hospedagemQuery2;
    private javax.persistence.Query hospedagemQuery3;
    private javax.swing.JButton jAdicionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFormattedTextField jDataentrada;
    private javax.swing.JFormattedTextField jDatasaida;
    private javax.swing.JTextField jIdhospedagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jNquarto;
    private javax.swing.JTextField jPreco;
    private javax.swing.JTextField jQtpessoas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
public Hospedagem telaHospedagem(){
 
    String nome= (this.jNome.getText());
    int qtpessoas= Integer.parseInt(this.jQtpessoas.getText());
     int nquarto= Integer.parseInt(this.jNquarto.getText());
   String preco= (this.jPreco.getText());
    String dataentrada= (this.jDataentrada.getText());
 String datasaida= (this.jDatasaida.getText());

        
  return (new Hospedagem ( nome,  nquarto, preco,qtpessoas, dataentrada, datasaida));  

}
   
    public void hospedagemTela(Hospedagem hospedagem){
     this.jIdhospedagem.setText(hospedagem.getIdhospedagem()+"");
        this.jNome.setText(hospedagem.getNome());
        this.jQtpessoas.setText(hospedagem.getQtpessoas()+"");
        this.jNquarto.setText(hospedagem.getNquarto()+"");
        this.jPreco.setText(hospedagem.getPreco());
       this.jDataentrada.setText(hospedagem.getDataentrada());
        this.jDatasaida.setText(hospedagem.getDatasaida());
      
        
        }
    public void limpaTela(){
       this.jIdhospedagem.setText("");
        this.jNome.setText("");
        this.jQtpessoas.setText("");
          this.jNquarto.setText("");
            this.jPreco.setText("");
               this.jDataentrada.setText("");
                this.jDatasaida.setText("");
                 

    
                
}
}
