/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import controle.Ctrllogin;
import javax.swing.ImageIcon;

import modelagem1.Login;

/**
 *
 * @author Dirceu
 */
   public class TelaLogin extends javax.swing.JFrame {
    private Ctrllogin login;


    /**
     * Creates new form TelaCandidato
     */
    public  TelaLogin() {
        initComponents();
            this.setLocationRelativeTo(null);
         this.setIconImage(new ImageIcon(getClass().
        getResource("ScreenHunter_06 Aug. 19 17.25.gif")).getImage());
          login= new Ctrllogin(); 
          this.setTitle("Modificar Usuario e Senha");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jVoltar = new javax.swing.JButton();
        jEditar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSenha = new javax.swing.JPasswordField();
        jRepetesenha = new javax.swing.JPasswordField();
        jUsuario = new javax.swing.JTextField();
        jId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField11.setText("jTextField11");

        jButton6.setText("jButton6");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ScreenHunter_05 May. 13 15.56.gif"))); // NOI18N

        jTextField7.setText("jTextField7");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ScreenHunter_05 May. 13 15.56.gif"))); // NOI18N
        jLabel15.setText("jLabel15");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ScreenHunter_05 May. 13 15.56.gif"))); // NOI18N
        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 70, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 60, -1));

        jVoltar.setBackground(new java.awt.Color(153, 255, 255));
        jVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/user8_16x16.gif"))); // NOI18N
        jVoltar.setText("Usuario Atual");
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, 30));

        jEditar.setBackground(new java.awt.Color(153, 255, 255));
        jEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEditar.setForeground(new java.awt.Color(255, 0, 0));
        jEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/user8_(edit)_16x16.gif"))); // NOI18N
        jEditar.setText("Modificar Usuario e senha");
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 190, -1, 30));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 128, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Confirmar Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, 20));

        jSenha.setText("jPasswordField1");
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 210, -1));

        jRepetesenha.setText("jPasswordField1");
        jRepetesenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRepetesenhaFocusLost(evt);
            }
        });
        getContentPane().add(jRepetesenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 210, -1));
        getContentPane().add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 210, -1));

        jId.setEnabled(false);
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 30, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ScreenHunter_71 Aug. 18 22.00.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/fd.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
      login.voltar();     
     this.loginTela(login.exibir());
    }//GEN-LAST:event_jVoltarActionPerformed

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
String senha = jSenha.getText();
String confirmarSenha = jRepetesenha.getText();
        
        if(jUsuario.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Usuario campo obrigatório","",2);
    return;
}  if(jSenha.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Senha campo obrigatório","",2);
    return;
} 

if(!senha.equals(confirmarSenha)){
 javax.swing.JOptionPane.showMessageDialog(null, "Senhas nao conferem!","",0);
 return;
}

 login.editar(this.telaLogin());
     this.loginTela(login.exibir());  
     javax.swing.JOptionPane.showMessageDialog(null, "Usuario e senha modificado com sucesso!");
    return;
    }//GEN-LAST:event_jEditarActionPerformed

    private void jRepetesenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRepetesenhaFocusLost
      String senha = jSenha.getText();
String confirmarSenha = jRepetesenha.getText();
if(!senha.equals(confirmarSenha)){
 javax.swing.JOptionPane.showMessageDialog(null, "Senhas nao conferem!","",0);
 return;
}
    }//GEN-LAST:event_jRepetesenhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jEditar;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jRepetesenha;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jUsuario;
    private javax.swing.JButton jVoltar;
    // End of variables declaration//GEN-END:variables
public Login telaLogin(){
    int id= Integer.parseInt(this.jId.getText());
    String usuario= (this.jUsuario.getText());
      String senha= (this.jSenha.getText());
    
     
  return (new Login (id,usuario,senha));  

   }
   
    public void loginTela(Login  login ){
        this.jId.setText(login.getId()+"");
        this.jUsuario.setText(login.getUsuario());
          this.jSenha.setText(login.getSenha());
      
        
        
        }
    public void limpaTela(){
        this.jId.setText("");
        this.jUsuario.setText("");
         this.jSenha.setText("");
      
         

    
                
}
}
