/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import com.mysql.jdbc.Connection;
import controle.CtrlReserva;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import modelagem1.Reserva;

/**
 *
 * @author Dirceu
 */
   public class TelaReserva extends javax.swing.JFrame {
    private CtrlReserva reserva;
 private NewMasterDetailForm veioDoNewMasterDetailForm  ;

    /**
     * Creates new form TelaCandidato
     */
    public  TelaReserva() {
        initComponents();
            this.setLocationRelativeTo(null);
        this.setTitle("Reserva");
         this.setIconImage(new ImageIcon(getClass(). getResource("ScreenHunter_06 Aug. 19 17.25.gif")).getImage());
          reserva= new CtrlReserva(); 
    }
public void  enviaPalavra (NewMasterDetailForm veiDo1,  String  nome){
             
              jNome.setText(nome);}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jNquarto = new javax.swing.JTextField();
        jQtpessoas = new javax.swing.JTextField();
        jNovo = new javax.swing.JButton();
        jAdicionar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jDataentrada = new javax.swing.JFormattedTextField();
        jDatasaida = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        jTextField11.setText("jTextField11");

        jButton6.setText("jButton6");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/ScreenHunter_05 May. 13 15.56.gif"))); // NOI18N

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel2.setText("Quarto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel3.setText("Qtpessoas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel4.setText("Dataentrada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 310, -1));

        jNquarto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNquartoFocusLost(evt);
            }
        });
        jNquarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNquartoMouseClicked(evt);
            }
        });
        getContentPane().add(jNquarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 110, -1));

        jQtpessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQtpessoasMouseClicked(evt);
            }
        });
        getContentPane().add(jQtpessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 110, -1));

        jNovo.setBackground(new java.awt.Color(153, 255, 255));
        jNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/edit_add.png"))); // NOI18N
        jNovo.setText("Novo");
        jNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 100, -1));

        jAdicionar.setBackground(new java.awt.Color(153, 255, 255));
        jAdicionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/filesave.png"))); // NOI18N
        jAdicionar.setText("Salvar");
        jAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 100, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 128, -1, -1));

        jLabel12.setText("Datasaida:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 20));

        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/search.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/filter.png"))); // NOI18N
        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Idreserva", "Nome", "Quarto", "Qtpessoas", "Dataentrada", "Datasaida"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 790, 250));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/print.png"))); // NOI18N
        jButton3.setText("Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 100, -1));

        try {
            jDataentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jDataentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, -1));

        try {
            jDatasaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jDatasaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/fd.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoActionPerformed
     jNome.setText(null);
      jQtpessoas.setText(null);
       jDataentrada.setText(null);
        jDatasaida.setText(null);
         jNquarto.setText(null);
         
    }//GEN-LAST:event_jNovoActionPerformed

    private void jAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarActionPerformed
       if(jNome.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Nome campo obrigatório","",2);
    return;

}if(jNquarto.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Quarto campo obrigatório","",2);
    return;
        }if(jDatasaida.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Data campo obrigatório","",2);
    return;
    }if(jDataentrada.getText().equals("")){
    javax.swing.JOptionPane.showMessageDialog(null, "Data campo obrigatório","",2);
    return;}
        
        
        javax.swing.JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
        reserva.adicionar(this.telaReserva());
     this.reservaTela(reserva.exibir());
    
    }//GEN-LAST:event_jAdicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
           conn =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
       String query="SELECT * FROM reserva WHERE nome LIKE ?";
       PreparedStatement cmd;
       cmd= conn.prepareStatement(query);
       cmd.setString(1,jTextField1.getText()+"%");
       ResultSet rs;
       rs= cmd.executeQuery();
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       model.setNumRows(0);
       
       while(rs.next()){
           
       model.addRow(
               new Object[]{
                   rs.getString("Idreserva"),
              rs.getString("Nome"),
               
            rs.getString("nquarto"),
              rs.getString("qtpessoas"),
               rs.getString("dataentrada") ,
              rs.getString("datasaida")
               }
               
       );
      
       }
       
        
        
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar a classe");
            
        } catch (SQLException ex) {
             System.out.println("Ocorreu error"+ ex.getMessage());
        }//Fim try
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
           conn =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
       String query="SELECT * FROM reserva  ";
       PreparedStatement cmd;
       cmd= conn.prepareStatement(query);
       
       ResultSet rs;
       rs= cmd.executeQuery();
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       model.setNumRows(0);
       
       while(rs.next()){
           
       model.addRow(
               new Object[]{
                  rs.getString("idreserva"),
              rs.getString("nome"),
               
            rs.getString("nquarto"),
              rs.getString("qtpessoas"),
               rs.getString("dataentrada") ,
              rs.getString("datasaida")
               }
       );
      
       }
       
        
        
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar a classe");
            
        } catch (SQLException ex) {
             System.out.println("Ocorreu error"+ ex.getMessage());
        }//Fim try
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   try {  
    // Imprime o coteudo da "jTable1":  
    jTable1.print(JTable.PrintMode.FIT_WIDTH);  
  
} catch (java.awt.print.PrinterException ex) {  
    JOptionPane.showMessageDialog(this, "Erro de impressão: " + ex.getMessage(), "Erro de impressão", JOptionPane.ERROR_MESSAGE);  
} 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jNquartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNquartoMouseClicked
       try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select * from quarto ");
              ResultSet rs = st.getResultSet();
              
              JPopupMenu popup1 = new JPopupMenu();
               JPopupMenu popup2 = new JPopupMenu();
                 JPopupMenu popup3 = new JPopupMenu();
                   JPopupMenu popup4 = new JPopupMenu();
                    JPopupMenu popup5 = new JPopupMenu();
                     JPopupMenu popup6 = new JPopupMenu();
                      JPopupMenu popup7 = new JPopupMenu();
                       JPopupMenu popup8 = new JPopupMenu();
                        JPopupMenu popup9 = new JPopupMenu();
                         JPopupMenu popup10 = new JPopupMenu();
     
                while (rs.next()){
         
                 // Especifica os dados em ordena.
      
        
             
         JMenuItem item = new JMenuItem(rs.getString("numero"));
        item.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
             
            jNquarto.setText(((JMenuItem) e.getSource()).getText());
            }
        });
        
         JMenuItem item1 = new JMenuItem( rs.getString("descrisao"));
        item1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
             
        
            }
        });
                //Adiciona item ao jText
              popup1.add(item);
             popup2.add(item);
              popup3.add(item);
              popup4.add(item);
               popup5.add(item);
              popup6.add(item);
              popup7.add(item);
              popup8.add(item);
               popup9.add(item);
              popup10.add(item);
              
               popup1.add(item1);
             popup2.add(item1);
              popup3.add(item1);
              popup4.add(item1);
               popup5.add(item1);
              popup6.add(item1);
              popup7.add(item1);
              popup8.add(item1);
               popup9.add(item1);
              popup10.add(item1);
              
                //Mostra na Tela
              popup1.show(jNquarto, 0, 30);
              popup2.show(jNquarto, 0, 30);
              popup3.show(jNquarto, 0, 30);
              popup4.show(jNquarto, 0, 30);
              popup5.show(jNquarto, 0, 30);
              popup6.show(jNquarto, 0, 30);
              popup7.show(jNquarto, 0, 30);
              popup8.show(jNquarto, 0, 30);
              popup9.show(jNquarto, 0, 30);
              popup10.show(jNquarto, 0, 30);
           
    
                }
             
                
           
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jNquarto, e);
        }//Fim try


    }//GEN-LAST:event_jNquartoMouseClicked

    private void jQtpessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQtpessoasMouseClicked
         //cria o primeiro item do menu e atribui uma ação pra ele
        JMenuItem item1 = new JMenuItem("1");
        item1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("1");
            }
        });

        //cria o segundo item do menu e atribui uma ação pra ele
        JMenuItem item2 = new JMenuItem("2");
        item2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
               jQtpessoas.setText("2");
            }
        });

        //cria o terceiro item do menu e atribui uma ação pra ele
        JMenuItem item3 = new JMenuItem("3");
        item3.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("3");
            }
        });
         JMenuItem item4 = new JMenuItem("4");
        item4.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("4");
            }
        });
         JMenuItem item5 = new JMenuItem("5");
        item5.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("5");
            }
        });
         JMenuItem item6 = new JMenuItem("6");
        item6.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jQtpessoas.setText("6");
            }
        });


        //cria o menu popup e adiciona os 3 itens
        JPopupMenu popup = new JPopupMenu();
        popup.add(item1);
        popup.add(item2);
        popup.add(item3);
        popup.add(item4);
        popup.add(item5);
        popup.add(item6);

        //mostra na tela
        popup.show(jQtpessoas, 0, 30);


    }//GEN-LAST:event_jQtpessoasMouseClicked

    private void jNquartoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNquartoFocusLost
             try {
              //Registra JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
 
            //Abrindo a conexão
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=convertToNull", "root", "root");
            
            //Executa a query de seleção
          
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT  *FROM hospedagem ORDER BY datasaida DESC");
              ResultSet rs = st.getResultSet();
        
                while (rs.next()){
        if(jNquarto.getText().equals(rs.getString("nquarto"))){
     javax.swing.JOptionPane.showMessageDialog(null, "Quarto "+(rs.getString("nquarto"))+" Ultima hospedagem:"+"\n"+
             "Data Entrada: "+(rs.getString("dataentrada"))+"\n"+"Data Saida: "+(rs.getString("datasaida")),"",0);
     return;
        }
                }
         } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(jNquarto, e);
        }//Fim try
    }//GEN-LAST:event_jNquartoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdicionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JFormattedTextField jDataentrada;
    private javax.swing.JFormattedTextField jDatasaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNome;
    private javax.swing.JButton jNovo;
    private javax.swing.JTextField jNquarto;
    private javax.swing.JTextField jQtpessoas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
public Reserva telaReserva(){

    String nome= (this.jNome.getText().trim());
    int qtpessoas= Integer.parseInt(this.jQtpessoas.getText());
     int nquarto= Integer.parseInt(this.jNquarto.getText());
  
    String dataentrada= (this.jDataentrada.getText().trim());
 String datasaida= (this.jDatasaida.getText());

        
  return (new Reserva ( nome, qtpessoas, nquarto,  dataentrada, datasaida));  

}
   
    public void reservaTela(Reserva reserva){
     
        this.jNome.setText(reserva.getNome());
        this.jQtpessoas.setText(reserva.getQtpessoas()+"");
      this.jNquarto.setText(reserva.getNquarto()+"");
       this.jDataentrada.setText(reserva.getDataentrada());
        this.jDatasaida.setText(reserva.getDatasaida());
      
        
        }
    public void limpaTela(){
      
        this.jNome.setText("");
        this.jQtpessoas.setText("");
          this.jNquarto.setText("");
           
               this.jDataentrada.setText("");
                this.jDatasaida.setText("");
                 

    
                
}
}
